### ISSUE TITLE
大佬，我有问题想请教

### ISSUE THREAD

**Issue by Utmostmao** [athlonreg/ASUS-F455LD-i5-4210u#10]
我按着教程弄了个opencore引导，可是开机到选择那里键盘没反应，然后自然启动只看到Windows选项，就启动Windows，问题出在什么地方，我很迷

**Comment by athlonreg** [comment]
有空我会更新一下oc的，目前这个机器已经不用了，，所以等一下吧，过几天有空了整一下

**Comment by Utmostmao** [comment]
机子不用还给大家弄，可以可以，你这个efi我用了两年，一边自己学，怎么都没学会，很好奇你是怎么学的，哈哈哈哈
上次反映的问题
1、之前旧版的话开机进度条一半的时候轻微抖一抖，我全面更新后严重了，直接黑一下屏
2、自动亮度失效了，偏好设置的开关还在，但是没能自动调节亮度（我记得之前好像是可以的）
3、偶尔关机不断电（极少），一般发生在重度使用后，这个问题一直都有
进系统后非常稳定，这真的超给好，谢谢你！

**Comment by athlonreg** [comment]
1. 黒一下闪一下或者花一下都是正常的，白果也会黒一下
2. 自动亮度试一下加上我刚更新的oc里面的SSDT-ALS0
3. 关机不断电这个问题没遇到过。。
4. oc我今天试着做了一份更新了，你可以试试看

**Comment by athlonreg** [comment]
580864366

这个是qq群号，可以加一下，任何问题在群里问都可以，即使我不在也会有人解答，github上经常收不到邮件，回复可能会不太及时。。。
