### ISSUE TITLE
OC not booting stuck booting screen please help me out

### ISSUE THREAD

**Issue by termi88** [athlonreg/ASUS-F455LD-i5-4210u#11]
![oc](https://user-images.githubusercontent.com/59068335/71209425-8601de00-22d1-11ea-87a0-e8b29df2fcc4.jpeg)
After END Random seed it does not boot please help me out

**Comment by athlonreg** [comment]
The laptop is not here.  So i will test it lately. Please wait.

**Comment by termi88** [comment]
> The laptop is not here. So i will test it lately. Please wait.

ok

**Comment by termi88** [comment]
> ![oc](https://user-images.githubusercontent.com/59068335/71209425-8601de00-22d1-11ea-87a0-e8b29df2fcc4.jpeg)
> After END Random seed it does not boot please help me out

I HAVE figured out the issue and got it fixed on my laptop  .. and i would like to thank you  supporting this laptop till now

**Comment by termi88** [comment]
but on mac os mac os catalina 10.15.2 wifi not working after trying every thing injected kexts but no wifi

**Comment by athlonreg** [comment]
> but on mac os mac os catalina 10.15.2 wifi not working after trying every thing injected kexts but no wifi

https://www.insanelymac.com/forum/files/file/956-atheros-installer-for-macos-mojave-and-catalina/

Maybe it can be tried. Good luck!

**Comment by athlonreg** [comment]
The boot stuck problem fixed.
