### ISSUE TITLE
你好，我的k555ld  跟你的配置可以说是一摸一样的，但有点看不懂目录结构，我直接用hotpatch 下的文件覆盖clover应该没问题吧

### ISSUE THREAD

**Issue by kongbg** [athlonreg/ASUS-F455LD-i5-4210u#7]

**Comment by athlonreg** [comment]
试一下就知道了

**Comment by kongbg** [comment]
谢谢。我们两台电脑只是cpu,显卡一样，其他的不一样，不过看不懂你这个怎么使用。最后我自己配了一个，已经放到github上了，无线网卡蓝牙不能用，还不能睡眠，电量不不能显示，不太完美。

**Comment by athlonreg** [comment]
无线要看型号的，如果也是ath9565的可以用我的，电池用我的hotpatch应该是可以的，不行的话只能自己写热补丁，等你无线电池可以了，睡眠估计也没问题了

**Comment by kongbg** [comment]
感谢，我有些是参考的你的，除了无线网卡之外，基本完美了。再次感谢
