### ISSUE TITLE
AsusPRO551LD_i5_4210U成功引导，感谢！

### ISSUE THREAD

**Issue by lanyun712** [athlonreg/ASUS-F455LD-i5-4210u#8]
特注册一个号来感谢一下，CPU和显卡一样，经过调试后麦克风，触摸板，电池电量用不了，其它正常，多谢！

**Comment by athlonreg** [comment]
用我的hotpatch应该是都可以的，记得把BIOS更新到最新

**Comment by wupanda0** [comment]
您好，我跟您是一样的机子，用您的EFI吃了两个月的黑苹果了，一切完美，只是这几天想尝试蓝牙键盘，发现蓝牙键盘总是搜索不到任何设备，请问您有遇到这样的问题吗？又是怎么解决的呢！求助！

**Comment by athlonreg** [comment]
> 您好，我跟您是一样的机子，用您的EFI吃了两个月的黑苹果了，一切完美，只是这几天想尝试蓝牙键盘，发现蓝牙键盘总是搜索不到任何设备，请问您有遇到这样的问题吗？又是怎么解决的呢！求助！

蓝牙无解

**Comment by wupanda0** [comment]
> > 您好，我跟您是一样的机子，用您的EFI吃了两个月的黑苹果了，一切完美，只是这几天想尝试蓝牙键盘，发现蓝牙键盘总是搜索不到任何设备，请问您有遇到这样的问题吗？又是怎么解决的呢！求助！
> 
> 蓝牙无解

好的，还是很感谢您！！
