### ISSUE TITLE
macOS 10.15 的问题

### ISSUE THREAD

**Issue by SerLinux** [athlonreg/ASUS-F455LD-i5-4210u#9]
10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢

**Comment by athlonreg** [comment]
> 10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢

详细报错发来，这个机器目前我不用了。。。

**Comment by Utmostmao** [comment]
我发现更新了整套efi后，有些地方（自动亮度，开机）没之前完整了，我怀疑自己没弄好，可是找不到原因，可以帮帮我吗

**Comment by athlonreg** [comment]
> 我发现更新了整套efi后，有些地方（自动亮度，开机）没之前完整了，我怀疑自己没弄好，可是找不到原因，可以帮帮我吗

详细情况说下。。自动亮度没了还是怎么着，开机有什么问题

**Comment by SerLinux** [comment]
> > 10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢
> 
> 详细报错发来，这个机器目前我不用了。。。

目前引导是黑果小兵的10.15.2+Hotpatch
上一次我用的是10.15正式版，卡在一堆SSDT错误
这一次10.15.2进去只有一行++++++++号，什么也没反应
这个是misc下的启动日志preboot，貌似找不到调试日志
感谢作者能从百忙中抽取时间来看
[preboot.log](https://github.com/athlonreg/ASUS-F455LD-i5-4210u/files/3992459/preboot.log)

**Comment by SerLinux** [comment]
> > 10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢
> 
> 详细报错发来，这个机器目前我不用了。。。

附一份DSDT
[DSDT-Origin-10.15.2.zip](https://github.com/athlonreg/ASUS-F455LD-i5-4210u/files/3992502/DSDT-Origin-10.15.2.zip)

**Comment by SerLinux** [comment]
> > 10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢
> 
> 详细报错发来，这个机器目前我不用了。。。

前一段时间把这个本本屏幕超频到了90Hz，不过个人感觉好像是驱动问题吧，都是10.14的，不知道大佬有什么看法
![log](https://user-images.githubusercontent.com/49341331/71322712-98645d80-2505-11ea-980a-1bfc83ad236a.png)

**Comment by athlonreg** [comment]
> > > 10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢
> > 
> > 
> > 详细报错发来，这个机器目前我不用了。。。
> 
> 前一段时间把这个本本屏幕超频到了90Hz，不过个人感觉好像是驱动问题吧，都是10.14的，不知道大佬有什么看法
> ![log](https://user-images.githubusercontent.com/49341331/71322712-98645d80-2505-11ea-980a-1bfc83ad236a.png)

这个是一些补丁的正常日志，没影响，我改天看一下原始dsdt把，现在仓库的clover应该是正常的，15需要把SSDT-EC放进去

**Comment by SerLinux** [comment]
> > > > 10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢
> > > 
> > > 
> > > 详细报错发来，这个机器目前我不用了。。。
> > 
> > 
> > 前一段时间把这个本本屏幕超频到了90Hz，不过个人感觉好像是驱动问题吧，都是10.14的，不知道大佬有什么看法
> > ![log](https://user-images.githubusercontent.com/49341331/71322712-98645d80-2505-11ea-980a-1bfc83ad236a.png)
> 
> 这个是一些补丁的正常日志，没影响，我改天看一下原始dsdt把，现在仓库的clover应该是正常的，15需要把SSDT-EC放进去

好的，谢谢大佬。期待有一天这个本本能稳定10.15，感谢

**Comment by athlonreg** [comment]
@SerLinux 你发的这个原始DSDT是X455LD的吗，是的话我就用这个整理hotpatch了

**Comment by athlonreg** [comment]
> > > > > 10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢
> > > > 
> > > > 
> > > > 详细报错发来，这个机器目前我不用了。。。
> > > 
> > > 
> > > 前一段时间把这个本本屏幕超频到了90Hz，不过个人感觉好像是驱动问题吧，都是10.14的，不知道大佬有什么看法
> > > ![log](https://user-images.githubusercontent.com/49341331/71322712-98645d80-2505-11ea-980a-1bfc83ad236a.png)
> > 
> > 
> > 这个是一些补丁的正常日志，没影响，我改天看一下原始dsdt把，现在仓库的clover应该是正常的，15需要把SSDT-EC放进去
> 
> 好的，谢谢大佬。期待有一天这个本本能稳定10.15，感谢

10.15应该稳定了，CLOVER之前让人帮忙测试了一下，没什么问题，OC我也更新了一下，可以试试看

**Comment by SerLinux** [comment]
> @SerLinux 你发的这个原始DSDT是X455LD的吗，是的话我就用这个整理hotpatch了

是原始DSDT，因为我也不会改....

**Comment by SerLinux** [comment]
> > > > > > 10.15 beta1的时候，引导成功，所有功能正常，但现在升级10.15正式版却不能开机，求大佬适配10.15，万分感谢
> > > > > 
> > > > > 
> > > > > 详细报错发来，这个机器目前我不用了。。。
> > > > 
> > > > 
> > > > 前一段时间把这个本本屏幕超频到了90Hz，不过个人感觉好像是驱动问题吧，都是10.14的，不知道大佬有什么看法
> > > > ![log](https://user-images.githubusercontent.com/49341331/71322712-98645d80-2505-11ea-980a-1bfc83ad236a.png)
> > > 
> > > 
> > > 这个是一些补丁的正常日志，没影响，我改天看一下原始dsdt把，现在仓库的clover应该是正常的，15需要把SSDT-EC放进去
> > 
> > 
> > 好的，谢谢大佬。期待有一天这个本本能稳定10.15，感谢
> 
> 10.15应该稳定了，CLOVER之前让人帮忙测试了一下，没什么问题，OC我也更新了一下，可以试试看

好哒，谢谢大佬
